//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionEducation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmissionEducation()
        {
            this.AdmissionEducationDetails = new HashSet<AdmissionEducationDetail>();
        }
    
        public int ID { get; set; }
        public int AdmissionID { get; set; }
        public int EducationLevelID { get; set; }
        public int MajorSubjectID { get; set; }
        public string Institute { get; set; }
        public string Title { get; set; }
        public string BoardOrganization { get; set; }
        public int PassingYear { get; set; }
        public decimal MarksObtained { get; set; }
        public decimal TotalMarks { get; set; }
        public string DMCAttachment { get; set; }
        public string CertificateAttachment { get; set; }
        public Nullable<bool> IsVerify { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual Admission Admission { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual MajorSubject MajorSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionEducationDetail> AdmissionEducationDetails { get; set; }
    }
}
