//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionPreference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmissionPreference()
        {
            this.AdmissionInterviewMarks = new HashSet<AdmissionInterviewMark>();
        }
    
        public int ID { get; set; }
        public int DepartmentProgramID { get; set; }
        public int AdmissionID { get; set; }
        public int EducationLevel_ID { get; set; }
        public string TestName { get; set; }
        public decimal ObtMarks { get; set; }
        public decimal TotalMarks { get; set; }
        public string RollNo { get; set; }
        public string PassingDate { get; set; }
        public string ValidUpto { get; set; }
        public string ScanCopy { get; set; }
        public Nullable<int> MeritListNo { get; set; }
        public Nullable<bool> IsAdmissionGranted { get; set; }
        public string BankVoucherNo { get; set; }
        public string BankName { get; set; }
        public string BranchCode { get; set; }
        public string BankBranch { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool IsPaid { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string Attachment { get; set; }
        public bool IsFake { get; set; }
        public Nullable<int> FakeBy { get; set; }
        public Nullable<System.DateTime> FakeDate { get; set; }
        public Nullable<int> OnlineVerifiedBy { get; set; }
        public string OnlinePaymentReferenceID { get; set; }
        public Nullable<System.DateTime> ReferenceIDCrDate { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual Admission Admission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionInterviewMark> AdmissionInterviewMarks { get; set; }
        public virtual DepartmentProgram DepartmentProgram { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
    }
}
