//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admission()
        {
            this.AdmissionEducations = new HashSet<AdmissionEducation>();
            this.AdmissionEducationDetails = new HashSet<AdmissionEducationDetail>();
            this.AdmissionPreferences = new HashSet<AdmissionPreference>();
            this.SessionWiseMeritListDets = new HashSet<SessionWiseMeritListDet>();
            this.Students = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public byte[] Photo { get; set; }
        public int TitleID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FatherCNIC { get; set; }
        public string FatherCNICCopy { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherOrganizationName { get; set; }
        public string FatherIncome { get; set; }
        public System.DateTime DOB { get; set; }
        public string EmailAddress { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string MobileNo { get; set; }
        public string GuardianMobileNo { get; set; }
        public string LandLineNo { get; set; }
        public string CNICNo { get; set; }
        public string CNICCopy { get; set; }
        public string PassportNo { get; set; }
        public string Gender { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public int ReligionID { get; set; }
        public int ProvinceID { get; set; }
        public int DistrictID { get; set; }
        public int DomicileID { get; set; }
        public int ApplicantID { get; set; }
        public int SessionID { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public string DescribeDisability { get; set; }
        public string SponsoredBy { get; set; }
        public bool AgreedUndertaking { get; set; }
        public bool AgreedUndertakingHSSCPart2 { get; set; }
        public Nullable<int> CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual District District { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Province Province { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Session Session { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionEducation> AdmissionEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionEducationDetail> AdmissionEducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionPreference> AdmissionPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWiseMeritListDet> SessionWiseMeritListDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
