//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantInterviewMark
    {
        public int ID { get; set; }
        public int ApplicantPreferenceID { get; set; }
        public decimal Motivation { get; set; }
        public decimal Relevancy { get; set; }
        public decimal TechnicalCompetence { get; set; }
        public decimal SOThinking { get; set; }
        public decimal Personalimpression { get; set; }
        public decimal CoverLetterMarks { get; set; }
        public string CoverLetter { get; set; }
        public decimal ResearchProposalMarks { get; set; }
        public string ResearchProposal { get; set; }
        public decimal CVMarks { get; set; }
        public string CV { get; set; }
        public decimal FirstRecommendationLetterMarks { get; set; }
        public string FirstRecommendationLetter { get; set; }
        public decimal SecondRecommendationLetterMarks { get; set; }
        public string SecondRecommendationLetter { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual ApplicantPreference ApplicantPreference { get; set; }
    }
}
