//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantPreference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicantPreference()
        {
            this.ApplicantInterviewMarks = new HashSet<ApplicantInterviewMark>();
        }
    
        public int ID { get; set; }
        public int DepartmentProgramID { get; set; }
        public int ApplicantID { get; set; }
        public int EducationLevel_ID { get; set; }
        public string TestName { get; set; }
        public decimal ObtMarks { get; set; }
        public decimal TotalMarks { get; set; }
        public string RollNo { get; set; }
        public string PassingDate { get; set; }
        public string ValidUpto { get; set; }
        public string ScanCopy { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantInterviewMark> ApplicantInterviewMarks { get; set; }
        public virtual Applicant Applicant { get; set; }
        public virtual DepartmentProgram DepartmentProgram { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
    }
}
