//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantEducationDetail
    {
        public int ID { get; set; }
        public int ApplicantID { get; set; }
        public int EducationLevelID { get; set; }
        public int MajorSubjectID { get; set; }
        public Nullable<int> MajorSubjectListOfCoursesID { get; set; }
        public int ApplicantEducationID { get; set; }
        public string CourseTitle { get; set; }
        public string CourseStudied { get; set; }
        public Nullable<int> ObtainMarks { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public int CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual ApplicantEducation ApplicantEducation { get; set; }
        public virtual Applicant Applicant { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual MajorSubject MajorSubject { get; set; }
    }
}
