//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentPolicy
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public Nullable<int> FinalMin { get; set; }
        public Nullable<int> FinalMax { get; set; }
        public Nullable<int> PreFinalMin { get; set; }
        public Nullable<int> PreFinalMax { get; set; }
        public Nullable<int> MidTermMin { get; set; }
        public Nullable<int> MidTermMax { get; set; }
        public Nullable<int> SessionalMin { get; set; }
        public Nullable<int> SessionalMax { get; set; }
        public Nullable<int> LabTaskMin { get; set; }
        public Nullable<int> LabTaskMax { get; set; }
        public Nullable<int> ACMID { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual ACM ACM { get; set; }
    }
}
