//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment()
        {
            this.AssessmentDetails = new HashSet<AssessmentDetail>();
            this.QPQuestionPapers = new HashSet<QPQuestionPaper>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public int TeacherCourseID { get; set; }
        public int AssessmentNameID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal TotalMarks { get; set; }
        public Nullable<decimal> Weightage { get; set; }
        public string MarksType { get; set; }
        public string Description { get; set; }
        public Nullable<int> PassingMarks { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public Nullable<System.TimeSpan> CrTime { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
        public Nullable<System.TimeSpan> UTime { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public string Attachment { get; set; }
        public bool IsLocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentDetail> AssessmentDetails { get; set; }
        public virtual AssessmentName AssessmentName { get; set; }
        public virtual TeacherCours TeacherCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPQuestionPaper> QPQuestionPapers { get; set; }
    }
}
