//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLO
    {
        public int ID { get; set; }
        public string CLOStatement { get; set; }
        public Nullable<int> CLONumber { get; set; }
        public int TaxonomyActionVerbID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> BOSID { get; set; }
        public Nullable<int> BOFID { get; set; }
        public Nullable<int> ACMID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string isNotActiveBy { get; set; }
        public Nullable<System.DateTime> isNotActiveDate { get; set; }
        public Nullable<System.TimeSpan> isNotActiveTime { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual ACM ACM { get; set; }
        public virtual BOF BOF { get; set; }
        public virtual BO BO { get; set; }
        public virtual Course Course { get; set; }
        public virtual TaxonomyActionVerb TaxonomyActionVerb { get; set; }
    }
}
