//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.BatchWiseCourses = new HashSet<BatchWiseCours>();
            this.CourseCoRequisites = new HashSet<CourseCoRequisite>();
            this.CourseCoRequisites1 = new HashSet<CourseCoRequisite>();
            this.CourseEquivalents = new HashSet<CourseEquivalent>();
            this.CourseEquivalents1 = new HashSet<CourseEquivalent>();
            this.CoursePreRequisites = new HashSet<CoursePreRequisite>();
            this.CoursePreRequisites1 = new HashSet<CoursePreRequisite>();
            this.CourseProgramLevels = new HashSet<CourseProgramLevel>();
            this.CoursePublications = new HashSet<CoursePublication>();
            this.StudentCourseDroppeds = new HashSet<StudentCourseDropped>();
            this.StudentCourses = new HashSet<StudentCours>();
            this.StudentCourseSelections = new HashSet<StudentCourseSelection>();
            this.StudentCourseWithDrawns = new HashSet<StudentCourseWithDrawn>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public int CrHr { get; set; }
        public Nullable<int> ContHr { get; set; }
        public string Description { get; set; }
        public string Objectives { get; set; }
        public string Outlines { get; set; }
        public Nullable<int> ACMID { get; set; }
        public Nullable<int> CourseCategoryInstitutionalID { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual ACM ACM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchWiseCours> BatchWiseCourses { get; set; }
        public virtual CourseCategoryInstitutional CourseCategoryInstitutional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCoRequisite> CourseCoRequisites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCoRequisite> CourseCoRequisites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseEquivalent> CourseEquivalents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseEquivalent> CourseEquivalents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursePreRequisite> CoursePreRequisites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursePreRequisite> CoursePreRequisites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseProgramLevel> CourseProgramLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursePublication> CoursePublications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseDropped> StudentCourseDroppeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCours> StudentCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseSelection> StudentCourseSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseWithDrawn> StudentCourseWithDrawns { get; set; }
    }
}
