//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentCoordinator
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> EmpFormID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string LetterOfAppointment { get; set; }
        public string LetterOfAppointmentReferNo { get; set; }
        public Nullable<System.DateTime> LetterOfAppointmentDate { get; set; }
        public string Other1 { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EmpForm EmpForm { get; set; }
    }
}
