//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.DepartmentCoordinators = new HashSet<DepartmentCoordinator>();
            this.DepartmentEmpForms = new HashSet<DepartmentEmpForm>();
            this.DepartmentHeads = new HashSet<DepartmentHead>();
            this.DepartmentPrograms = new HashSet<DepartmentProgram>();
            this.BOS = new HashSet<BO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public int TypeID { get; set; }
        public int FacultyID { get; set; }
        public int HODID { get; set; }
        public int CoordinatorID { get; set; }
        public string Location { get; set; }
        public string ContactNo { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
    
        public virtual Campus Campus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentCoordinator> DepartmentCoordinators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentEmpForm> DepartmentEmpForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentHead> DepartmentHeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentProgram> DepartmentPrograms { get; set; }
        public virtual DepartmentType DepartmentType { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BO> BOS { get; set; }
    }
}
