//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepartmentProgram()
        {
            this.AdmissionPreferences = new HashSet<AdmissionPreference>();
            this.ApplicantPreferences = new HashSet<ApplicantPreference>();
            this.MeritListMarksCriterias = new HashSet<MeritListMarksCriteria>();
            this.ProgramEligibilities = new HashSet<ProgramEligibility>();
            this.ProgramOffereds = new HashSet<ProgramOffered>();
            this.ProgramPreferences = new HashSet<ProgramPreference>();
            this.SessionWiseMeritListDets = new HashSet<SessionWiseMeritListDet>();
            this.SessionWiseMeritLists = new HashSet<SessionWiseMeritList>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public int ProgramID { get; set; }
        public int DepartmentID { get; set; }
        public int CreditHours { get; set; }
        public int Duration { get; set; }
        public int TotalSemesters { get; set; }
        public Nullable<int> Repeat { get; set; }
        public Nullable<int> Probation { get; set; }
        public Nullable<int> IOG { get; set; }
        public Nullable<int> CourseRepeat { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionPreference> AdmissionPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantPreference> ApplicantPreferences { get; set; }
        public virtual Department Department { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeritListMarksCriteria> MeritListMarksCriterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramEligibility> ProgramEligibilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramOffered> ProgramOffereds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramPreference> ProgramPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWiseMeritListDet> SessionWiseMeritListDets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWiseMeritList> SessionWiseMeritLists { get; set; }
    }
}
