//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSendingBox
    {
        public int ID { get; set; }
        public string emailAddress { get; set; }
        public Nullable<System.DateTime> dateOfSchedule { get; set; }
        public Nullable<System.TimeSpan> timeOFSchedule { get; set; }
        public string fromEmail { get; set; }
        public string messageTitle { get; set; }
        public string messageBody { get; set; }
        public byte[] Attachment1 { get; set; }
        public byte[] Attachment2 { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    }
}
