//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpForm()
        {
            this.CMSUsers = new HashSet<CMSUser>();
            this.DepartmentCoordinators = new HashSet<DepartmentCoordinator>();
            this.DepartmentEmpForms = new HashSet<DepartmentEmpForm>();
            this.DepartmentHeads = new HashSet<DepartmentHead>();
            this.EmpExperiences = new HashSet<EmpExperience>();
            this.FacultyHeads = new HashSet<FacultyHead>();
            this.ProgramCoordinators = new HashSet<ProgramCoordinator>();
            this.EmpFormJobNatures = new HashSet<EmpFormJobNature>();
            this.EmpFormJobTypes = new HashSet<EmpFormJobType>();
            this.EmpQualifications = new HashSet<EmpQualification>();
            this.EmpReferences = new HashSet<EmpReference>();
            this.EmpTrainings = new HashSet<EmpTraining>();
            this.ProjectInvestigatedByEmpForms = new HashSet<ProjectInvestigatedByEmpForm>();
            this.SessionWiseMeritLists = new HashSet<SessionWiseMeritList>();
            this.SessionWiseMeritLists1 = new HashSet<SessionWiseMeritList>();
            this.StudentCourseSelections = new HashSet<StudentCourseSelection>();
            this.StudentsAdvisors = new HashSet<StudentsAdvisor>();
            this.StudentsSupervisors = new HashSet<StudentsSupervisor>();
            this.TeacherCourses = new HashSet<TeacherCours>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string Name { get; set; }
        public string SecondaryEmailAddress { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public string OfficialEmailAddress { get; set; }
        public string MartialStatus { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string HusbandName { get; set; }
        public string HusbandOccupation { get; set; }
        public string MotherTongue { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> FireDate { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string JoiningLetter { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> EmpDesignationID { get; set; }
        public string CNIC { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string WhatsAppNo { get; set; }
        public string LandLine { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> DomicileID { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public string EOBINO { get; set; }
        public Nullable<int> TelExtension { get; set; }
        public bool IsActive { get; set; }
        public bool IsExpelled { get; set; }
        public bool IsBlock { get; set; }
        public Nullable<int> HRnumber { get; set; }
        public string HiringLetterReferenceNo { get; set; }
        public string HiringLetterCopy { get; set; }
        public string FireReason { get; set; }
        public string FireLetterCopy { get; set; }
        public string CNICCopy { get; set; }
        public string CNICCopyBack { get; set; }
        public string Passport { get; set; }
        public string PassportCopy { get; set; }
        public Nullable<int> PresentNationalityID { get; set; }
        public Nullable<int> PresentProvinceID { get; set; }
        public Nullable<int> PresentDistrictID { get; set; }
        public string MobileEmergency { get; set; }
        public Nullable<int> PermanentNationalityID { get; set; }
        public Nullable<int> PermanentProvinceID { get; set; }
        public Nullable<int> PermanentDistrictID { get; set; }
        public string DomicileCopy { get; set; }
        public string BloodGroup { get; set; }
        public string NextOfKinName { get; set; }
        public string NextOfKinRelationship { get; set; }
        public string NextOfKinPhoto { get; set; }
        public string NextOfKinCNIC { get; set; }
        public string NextOfKinMobile { get; set; }
        public Nullable<System.DateTime> NextOfKinUDate { get; set; }
        public Nullable<System.TimeSpan> NextofKinTime { get; set; }
        public string Color { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string Section { get; set; }
    
        public virtual Campus Campus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMSUser> CMSUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentCoordinator> DepartmentCoordinators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentEmpForm> DepartmentEmpForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentHead> DepartmentHeads { get; set; }
        public virtual District District { get; set; }
        public virtual District District1 { get; set; }
        public virtual District District2 { get; set; }
        public virtual EmpDesignation EmpDesignation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpExperience> EmpExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacultyHead> FacultyHeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramCoordinator> ProgramCoordinators { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Nationality Nationality1 { get; set; }
        public virtual Province Province { get; set; }
        public virtual Province Province1 { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Role Role { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpFormJobNature> EmpFormJobNatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpFormJobType> EmpFormJobTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpQualification> EmpQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpReference> EmpReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpTraining> EmpTrainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInvestigatedByEmpForm> ProjectInvestigatedByEmpForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWiseMeritList> SessionWiseMeritLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWiseMeritList> SessionWiseMeritLists1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseSelection> StudentCourseSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsAdvisor> StudentsAdvisors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsSupervisor> StudentsSupervisors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherCours> TeacherCourses { get; set; }
    }
}
