//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpQualification
    {
        public int ID { get; set; }
        public int FormID { get; set; }
        public int EducationLevelID { get; set; }
        public string EducationTitle { get; set; }
        public string Institute { get; set; }
        public string DivisionGrade { get; set; }
        public string MajorSubjects { get; set; }
        public string PassingYear { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual EmpForm EmpForm { get; set; }
    }
}
