//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACM> ACMs { get; set; }
        public virtual DbSet<Admission> Admissions { get; set; }
        public virtual DbSet<AdmissionEducation> AdmissionEducations { get; set; }
        public virtual DbSet<AdmissionEducationDetail> AdmissionEducationDetails { get; set; }
        public virtual DbSet<AdmissionInterviewMark> AdmissionInterviewMarks { get; set; }
        public virtual DbSet<AdmissionPreference> AdmissionPreferences { get; set; }
        public virtual DbSet<ApiException> ApiExceptions { get; set; }
        public virtual DbSet<ApplicantEducation> ApplicantEducations { get; set; }
        public virtual DbSet<ApplicantEducationDetail> ApplicantEducationDetails { get; set; }
        public virtual DbSet<ApplicantInterviewMark> ApplicantInterviewMarks { get; set; }
        public virtual DbSet<ApplicantPreference> ApplicantPreferences { get; set; }
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<AssessmentPolicy> AssessmentPolicies { get; set; }
        public virtual DbSet<BatchWiseCours> BatchWiseCourses { get; set; }
        public virtual DbSet<Board> Boards { get; set; }
        public virtual DbSet<BOF> BOFs { get; set; }
        public virtual DbSet<BO> BOS { get; set; }
        public virtual DbSet<Campus> Campuses { get; set; }
        public virtual DbSet<CMSUser> CMSUsers { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseCategoryInstitutional> CourseCategoryInstitutionals { get; set; }
        public virtual DbSet<CourseCoRequisite> CourseCoRequisites { get; set; }
        public virtual DbSet<CourseEquivalent> CourseEquivalents { get; set; }
        public virtual DbSet<CoursePreRequisite> CoursePreRequisites { get; set; }
        public virtual DbSet<CourseProgramLevel> CourseProgramLevels { get; set; }
        public virtual DbSet<CoursePublication> CoursePublications { get; set; }
        public virtual DbSet<DBCredential> DBCredentials { get; set; }
        public virtual DbSet<DepartmentCoordinator> DepartmentCoordinators { get; set; }
        public virtual DbSet<DepartmentEmpForm> DepartmentEmpForms { get; set; }
        public virtual DbSet<DepartmentHead> DepartmentHeads { get; set; }
        public virtual DbSet<DepartmentProgram> DepartmentPrograms { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentType> DepartmentTypes { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<EducationLevel> EducationLevels { get; set; }
        public virtual DbSet<EmailSendingBox> EmailSendingBoxes { get; set; }
        public virtual DbSet<EmailSettingsTestApplicant> EmailSettingsTestApplicants { get; set; }
        public virtual DbSet<EmpDesignation> EmpDesignations { get; set; }
        public virtual DbSet<EmpExperience> EmpExperiences { get; set; }
        public virtual DbSet<EmpForm> EmpForms { get; set; }
        public virtual DbSet<EmpFormJobNature> EmpFormJobNatures { get; set; }
        public virtual DbSet<EmpFormJobPosition> EmpFormJobPositions { get; set; }
        public virtual DbSet<EmpFormJobScale> EmpFormJobScales { get; set; }
        public virtual DbSet<EmpFormJobType> EmpFormJobTypes { get; set; }
        public virtual DbSet<EmpLinguisticSkill> EmpLinguisticSkills { get; set; }
        public virtual DbSet<EmpQualification> EmpQualifications { get; set; }
        public virtual DbSet<EmpReference> EmpReferences { get; set; }
        public virtual DbSet<EmpTraining> EmpTrainings { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FacultyHead> FacultyHeads { get; set; }
        public virtual DbSet<FeeCriteria> FeeCriterias { get; set; }
        public virtual DbSet<FeeHead> FeeHeads { get; set; }
        public virtual DbSet<FinanceUnpaidDataForLMControl> FinanceUnpaidDataForLMControls { get; set; }
        public virtual DbSet<Grading> Gradings { get; set; }
        public virtual DbSet<GradingPolicy> GradingPolicies { get; set; }
        public virtual DbSet<JobNature> JobNatures { get; set; }
        public virtual DbSet<JobPosition> JobPositions { get; set; }
        public virtual DbSet<JobScale> JobScales { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<MajorSubject> MajorSubjects { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MeritListMarksCriteria> MeritListMarksCriterias { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<OnlinePaymentMapping> OnlinePaymentMappings { get; set; }
        public virtual DbSet<OnlinePaymentVender> OnlinePaymentVenders { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrganizationLegalType> OrganizationLegalTypes { get; set; }
        public virtual DbSet<OrganizationSectorType> OrganizationSectorTypes { get; set; }
        public virtual DbSet<ProgramCoordinator> ProgramCoordinators { get; set; }
        public virtual DbSet<ProgramEligibility> ProgramEligibilities { get; set; }
        public virtual DbSet<ProgramLevel> ProgramLevels { get; set; }
        public virtual DbSet<ProgramOffered> ProgramOffereds { get; set; }
        public virtual DbSet<ProgramPreference> ProgramPreferences { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectAwardedByOrganization> ProjectAwardedByOrganizations { get; set; }
        public virtual DbSet<ProjectInvestigatedByEmpForm> ProjectInvestigatedByEmpForms { get; set; }
        public virtual DbSet<ProjectInvestigatedByStudent> ProjectInvestigatedByStudents { get; set; }
        public virtual DbSet<ProjectInvestigationType> ProjectInvestigationTypes { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<PublicationType> PublicationTypes { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleWiseMenu> RoleWiseMenus { get; set; }
        public virtual DbSet<ScholarshipHead> ScholarshipHeads { get; set; }
        public virtual DbSet<ScholarshipHeadsApplyOnFeeHead> ScholarshipHeadsApplyOnFeeHeads { get; set; }
        public virtual DbSet<SemesterCourseLoad> SemesterCourseLoads { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionWiseMeritList> SessionWiseMeritLists { get; set; }
        public virtual DbSet<SessionWiseMeritListDet> SessionWiseMeritListDets { get; set; }
        public virtual DbSet<SMSConfig> SMSConfigs { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendances { get; set; }
        public virtual DbSet<StudentCourseDropped> StudentCourseDroppeds { get; set; }
        public virtual DbSet<StudentCours> StudentCourses { get; set; }
        public virtual DbSet<StudentCourseSelection> StudentCourseSelections { get; set; }
        public virtual DbSet<StudentCourseWithDrawn> StudentCourseWithDrawns { get; set; }
        public virtual DbSet<StudentFee> StudentFees { get; set; }
        public virtual DbSet<StudentProgramChangeHistory> StudentProgramChangeHistories { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsAdvisor> StudentsAdvisors { get; set; }
        public virtual DbSet<StudentSemester> StudentSemesters { get; set; }
        public virtual DbSet<StudentsIDcard> StudentsIDcards { get; set; }
        public virtual DbSet<StudentsSupervisor> StudentsSupervisors { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<TeacherAttendance> TeacherAttendances { get; set; }
        public virtual DbSet<TeacherCours> TeacherCourses { get; set; }
        public virtual DbSet<TestApplicant> TestApplicants { get; set; }
        public virtual DbSet<TestCalender> TestCalenders { get; set; }
        public virtual DbSet<TestCenter> TestCenters { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestSession> TestSessions { get; set; }
        public virtual DbSet<TestVoucher> TestVouchers { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<MajorSubjectListOfCours> MajorSubjectListOfCourses { get; set; }
        public virtual DbSet<v_MeritList> v_MeritList { get; set; }
        public virtual DbSet<v_TestAdmitCard> v_TestAdmitCard { get; set; }
        public virtual DbSet<v_TestCalenders> v_TestCalenders { get; set; }
        public virtual DbSet<v_TestVouchers> v_TestVouchers { get; set; }
    }
}
