//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.ProjectAwardedByOrganizations = new HashSet<ProjectAwardedByOrganization>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int OrganizationLegalTypeID { get; set; }
        public int OrganizationSectorTypeID { get; set; }
        public Nullable<System.DateTime> FoundedDate { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Landline { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CEOName { get; set; }
        public string FocalPersonName { get; set; }
        public string FocalPersonMobile { get; set; }
        public string FocalPersonEmail { get; set; }
        public Nullable<int> EmployeeCount { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<bool> IsPubliclyTraded { get; set; }
        public string StockSymbol { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.TimeSpan> CrTime { get; set; }
        public Nullable<System.TimeSpan> UTime { get; set; }
    
        public virtual OrganizationLegalType OrganizationLegalType { get; set; }
        public virtual OrganizationSectorType OrganizationSectorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAwardedByOrganization> ProjectAwardedByOrganizations { get; set; }
    }
}
