//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.DepartmentPrograms = new HashSet<DepartmentProgram>();
            this.ProgramCoordinators = new HashSet<ProgramCoordinator>();
            this.PEOs = new HashSet<PEO>();
            this.PLOes = new HashSet<PLO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public int ProgramLevel_ID { get; set; }
        public Nullable<int> ACMID { get; set; }
        public Nullable<int> BOFID { get; set; }
        public Nullable<int> BOSID { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramTitle { get; set; }
        public string ShortAlpha { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual ACM ACM { get; set; }
        public virtual BOF BOF { get; set; }
        public virtual BO BO { get; set; }
        public virtual Campus Campus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentProgram> DepartmentPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramCoordinator> ProgramCoordinators { get; set; }
        public virtual ProgramLevel ProgramLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEO> PEOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLO> PLOes { get; set; }
    }
}
