//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAwardedByOrganization
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<decimal> FundedAmount { get; set; }
        public string AwardLetter { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
        public string AwardLocation { get; set; }
        public string AwardType { get; set; }
        public string AwardStatus { get; set; }
        public string GrantReference { get; set; }
        public string ContractNumber { get; set; }
        public string FundingSource { get; set; }
        public string Comments { get; set; }
        public string AwardFocalPersonName { get; set; }
        public string AwardFocalPersonMobile { get; set; }
        public string AwardFocalPersonEmail { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.TimeSpan> CrTime { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.TimeSpan> Utime { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Project Project { get; set; }
    }
}
