//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectAwardedByOrganizations = new HashSet<ProjectAwardedByOrganization>();
            this.ProjectInvestigatedByEmpForms = new HashSet<ProjectInvestigatedByEmpForm>();
            this.ProjectInvestigatedByStudents = new HashSet<ProjectInvestigatedByStudent>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ProjectTypeID { get; set; }
        public Nullable<decimal> FundingAmount { get; set; }
        public Nullable<bool> IsFunded { get; set; }
        public Nullable<bool> IsAwarded { get; set; }
        public Nullable<bool> IsClassified { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PositionForBSStudents { get; set; }
        public Nullable<int> PositionForMSStudents { get; set; }
        public Nullable<int> PositionForPhDStudents { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.TimeSpan> UTime { get; set; }
        public Nullable<int> CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<System.TimeSpan> CTime { get; set; }
    
        public virtual ProjectType ProjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAwardedByOrganization> ProjectAwardedByOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInvestigatedByEmpForm> ProjectInvestigatedByEmpForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInvestigatedByStudent> ProjectInvestigatedByStudents { get; set; }
    }
}
