//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.CoursePublications = new HashSet<CoursePublication>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Edition { get; set; }
        public Nullable<System.DateTime> DateOfPublication { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string PublicationWebLink { get; set; }
        public string PublisherWebLink { get; set; }
        public string DOI { get; set; }
        public string ISSN { get; set; }
        public string Venue { get; set; }
        public string Pages { get; set; }
        public Nullable<int> PublicationTypeID { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursePublication> CoursePublications { get; set; }
        public virtual PublicationType PublicationType { get; set; }
    }
}
