//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QPQuestionPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QPQuestionPaper()
        {
            this.QPSections = new HashSet<QPSection>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public Nullable<System.DateTime> PaperScheduledDate { get; set; }
        public Nullable<System.TimeSpan> PaperStartTime { get; set; }
        public string QPType { get; set; }
        public string Instructions { get; set; }
        public Nullable<decimal> MaximumMarks { get; set; }
        public Nullable<decimal> PassingMarks { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.TimeSpan> CrTime { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.TimeSpan> UTime { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPSection> QPSections { get; set; }
    }
}
