//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QPQuestion
    {
        public int ID { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> CLOID { get; set; }
        public Nullable<int> QuestionTypeID { get; set; }
        public string Instructions { get; set; }
        public string QuestionText { get; set; }
        public Nullable<decimal> MaximumMarks { get; set; }
        public Nullable<decimal> PassingMarks { get; set; }
        public string Attachment { get; set; }
        public string AttachmentRefTitle { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.TimeSpan> CrTime { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.TimeSpan> UTime { get; set; }
    
        public virtual CLO CLO { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual QPSection QPSection { get; set; }
    }
}
