//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QPSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QPSection()
        {
            this.QPQuestions = new HashSet<QPQuestion>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<int> QuestionPaperId { get; set; }
        public string Name { get; set; }
        public string Attachment { get; set; }
        public string AttachmentRefTitle { get; set; }
        public string Instructions { get; set; }
        public Nullable<decimal> MaximumMarks { get; set; }
        public Nullable<decimal> PassingMarks { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public bool OnSeparatePages { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.TimeSpan> CrTime { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.TimeSpan> UTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPQuestion> QPQuestions { get; set; }
        public virtual QPQuestionPaper QPQuestionPaper { get; set; }
    }
}
