//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleWiseMenu
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public int MenuID { get; set; }
        public int SubMenuID { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Role Role { get; set; }
        public virtual SubMenu SubMenu { get; set; }
    }
}
