//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionWiseMeritList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionWiseMeritList()
        {
            this.SessionWiseMeritListDets = new HashSet<SessionWiseMeritListDet>();
        }
    
        public int ID { get; set; }
        public int SessionID { get; set; }
        public int DepartmentProgramID { get; set; }
        public int MeritListNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsRecommended { get; set; }
        public Nullable<int> RecommendedBy { get; set; }
        public Nullable<System.DateTime> RecommendedDate { get; set; }
        public string RecommendedRemarks { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> ApprovalRequestBy { get; set; }
        public Nullable<System.DateTime> ApprovalRequestDate { get; set; }
        public string ApprovalRemarks { get; set; }
        public bool IsOfferLetterSent { get; set; }
        public Nullable<int> OfferLetterSendBy { get; set; }
        public Nullable<System.DateTime> OfferLetterSendDate { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual DepartmentProgram DepartmentProgram { get; set; }
        public virtual EmpForm EmpForm { get; set; }
        public virtual EmpForm EmpForm1 { get; set; }
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWiseMeritListDet> SessionWiseMeritListDets { get; set; }
    }
}
