//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSemester
    {
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public int SemesterNo { get; set; }
        public int ScholorshipHeadID { get; set; }
        public double SGPA { get; set; }
        public double CGPA { get; set; }
        public Nullable<int> TotalTakenCrHr { get; set; }
        public Nullable<int> TotalEarnedCrHr { get; set; }
        public bool ResultFinalized { get; set; }
        public Nullable<int> Probation { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
