//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentCours()
        {
            this.StudentsSupervisors = new HashSet<StudentsSupervisor>();
            this.SurveyInitiatedResponses = new HashSet<SurveyInitiatedResponse>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public int TeacherCourseID { get; set; }
        public string Section { get; set; }
        public Nullable<int> TakenCrHr { get; set; }
        public Nullable<int> EarnedCrHr { get; set; }
        public Nullable<double> GP { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> GradingDate { get; set; }
        public Nullable<System.TimeSpan> GradingTime { get; set; }
        public Nullable<int> GradingBy { get; set; }
        public bool IsCourseLock { get; set; }
        public bool IsResultFinalized { get; set; }
        public Nullable<System.DateTime> ResultFinalizedDate { get; set; }
        public Nullable<System.TimeSpan> ResultFinalizedTime { get; set; }
        public Nullable<int> ResultFinalizedBy { get; set; }
        public bool IsRepeated { get; set; }
        public bool IsMakeUp { get; set; }
        public bool IsDropped { get; set; }
        public Nullable<System.DateTime> IsDroppedDate { get; set; }
        public Nullable<System.TimeSpan> IsDroppedTime { get; set; }
        public Nullable<int> IsDroppedBy { get; set; }
        public bool IsWithdraw { get; set; }
        public Nullable<System.DateTime> IsWithdrawDate { get; set; }
        public Nullable<System.TimeSpan> IsWithdrawTime { get; set; }
        public Nullable<int> IsWithdrawBy { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Course Course { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsSupervisor> StudentsSupervisors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyInitiatedResponse> SurveyInitiatedResponses { get; set; }
    }
}
