//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgramChangeHistory
    {
        public int ID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public int StudentID { get; set; }
        public int FromBatchID { get; set; }
        public int ToBatchID { get; set; }
        public string OldRegNo { get; set; }
        public string NewRegNo { get; set; }
        public int DuringSemesterNo { get; set; }
        public int ToSemesterNo { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public System.TimeSpan ChangedTime { get; set; }
        public int ChangedBy { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
