//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseSelection
    {
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public int SessionID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public System.DateTime CourseRequestedDate { get; set; }
        public System.TimeSpan CourseRequestedTime { get; set; }
        public Nullable<System.DateTime> CourseApprovalDate { get; set; }
        public Nullable<System.TimeSpan> CourseApprovalTime { get; set; }
        public Nullable<int> CourseApprovalBy { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual Course Course { get; set; }
        public virtual EmpForm EmpForm { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
