//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ProjectInvestigatedByStudents = new HashSet<ProjectInvestigatedByStudent>();
            this.StudentAttendances = new HashSet<StudentAttendance>();
            this.StudentCourseDroppeds = new HashSet<StudentCourseDropped>();
            this.StudentCourses = new HashSet<StudentCours>();
            this.StudentCourseSelections = new HashSet<StudentCourseSelection>();
            this.StudentCourseWithDrawns = new HashSet<StudentCourseWithDrawn>();
            this.StudentFees = new HashSet<StudentFee>();
            this.StudentsAdvisors = new HashSet<StudentsAdvisor>();
            this.StudentSemesters = new HashSet<StudentSemester>();
            this.StudentsIDcards = new HashSet<StudentsIDcard>();
            this.StudentsSupervisors = new HashSet<StudentsSupervisor>();
        }
    
        public int ID { get; set; }
        public int AdmissionID { get; set; }
        public int BatchID { get; set; }
        public string RegNo { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public bool IsFreezed { get; set; }
        public Nullable<int> IsFreezedBy { get; set; }
        public Nullable<System.DateTime> IsFreezedDate { get; set; }
        public bool IsAdmissionCancelled { get; set; }
        public Nullable<int> IsAdmissionCancelledBy { get; set; }
        public Nullable<System.DateTime> IsAdmissionCancelledDate { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual Admission Admission { get; set; }
        public virtual ProgramOffered ProgramOffered { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInvestigatedByStudent> ProjectInvestigatedByStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseDropped> StudentCourseDroppeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCours> StudentCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseSelection> StudentCourseSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseWithDrawn> StudentCourseWithDrawns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFee> StudentFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsAdvisor> StudentsAdvisors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSemester> StudentSemesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsIDcard> StudentsIDcards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsSupervisor> StudentsSupervisors { get; set; }
    }
}
