//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int ID { get; set; }
        public int CampusID { get; set; }
        public int SessionID { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public string Section { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public bool IsPresent { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public System.TimeSpan AttendanceTime { get; set; }
        public string AttendanceType { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<int> UBy { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
