//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyInitiatedResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyInitiatedResponse()
        {
            this.SurveyHeadingQAResponses = new HashSet<SurveyHeadingQAResponse>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SurveyInititatedID { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<int> StudentCourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TeacherCoursesID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Section { get; set; }
        public Nullable<bool> Submitted { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.TimeSpan> SubmittedTime { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.TimeSpan> CrTime { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<System.TimeSpan> UTime { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Session Session { get; set; }
        public virtual StudentCours StudentCours { get; set; }
        public virtual Student Student { get; set; }
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyHeadingQAResponse> SurveyHeadingQAResponses { get; set; }
        public virtual SurveyInitiated SurveyInitiated { get; set; }
        public virtual TeacherCours TeacherCours { get; set; }
    }
}
