//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyHeadingQA
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public int QuestionTypeID { get; set; }
        public string AnswerInDescription { get; set; }
        public int SurveyHeadingID { get; set; }
        public Nullable<bool> StronglyDisagree { get; set; }
        public Nullable<bool> Disagree { get; set; }
        public Nullable<bool> Uncertain { get; set; }
        public Nullable<bool> Agree { get; set; }
        public Nullable<bool> StronglyAgree { get; set; }
        public Nullable<int> SortNo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> isNotActiveBy { get; set; }
        public Nullable<System.DateTime> isNotActiveDate { get; set; }
        public Nullable<System.TimeSpan> isNotActiveTime { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual QuestionType QuestionType { get; set; }
        public virtual SurveyHeading SurveyHeading { get; set; }
    }
}
