//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomyLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxonomyLevel()
        {
            this.TaxonomyActionVerbs = new HashSet<TaxonomyActionVerb>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LevelNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> TaxonomyDomainID { get; set; }
        public Nullable<int> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxonomyActionVerb> TaxonomyActionVerbs { get; set; }
        public virtual TaxonomyDomain TaxonomyDomain { get; set; }
    }
}
