//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherCours
    {
        public int ID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public Nullable<int> EmpFormID { get; set; }
        public int SessionID { get; set; }
        public int CourseID { get; set; }
        public string Section { get; set; }
        public bool Finalized { get; set; }
        public int CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public int UBy { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual EmpForm EmpForm { get; set; }
        public virtual Session Session { get; set; }
    }
}
