//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestVoucher
    {
        public int ID { get; set; }
        public Nullable<int> TestApplicantID { get; set; }
        public int VoucherNo { get; set; }
        public int ApplicantID { get; set; }
        public int TestID { get; set; }
        public int TestSessionID { get; set; }
        public decimal Amount { get; set; }
        public string BankVoucherNo { get; set; }
        public string BankName { get; set; }
        public string BranchCode { get; set; }
        public string BankBranch { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool IsPaid { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string Attachment { get; set; }
        public bool IsFake { get; set; }
        public Nullable<int> FakeBy { get; set; }
        public Nullable<System.DateTime> FakeDate { get; set; }
        public Nullable<int> OnlineVerifiedBy { get; set; }
        public string OnlinePaymentReferenceID { get; set; }
        public Nullable<System.DateTime> ReferenceIDCrDate { get; set; }
        public Nullable<int> CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual TestApplicant TestApplicant { get; set; }
        public virtual Test Test { get; set; }
        public virtual TestSession TestSession { get; set; }
    }
}
