//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestApplicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestApplicant()
        {
            this.TestVouchers = new HashSet<TestVoucher>();
        }
    
        public int ID { get; set; }
        public int ApplicantID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> TestCenterID { get; set; }
        public Nullable<int> TestCalenderID { get; set; }
        public bool IsAttend { get; set; }
        public string TestPassword { get; set; }
        public Nullable<int> ObtainMarks { get; set; }
        public int TotalMarks { get; set; }
        public Nullable<int> CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public Nullable<int> UBy { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual TestCalender TestCalender { get; set; }
        public virtual TestCenter TestCenter { get; set; }
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestVoucher> TestVouchers { get; set; }
    }
}
