//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_MeritList
    {
        public int ID { get; set; }
        public byte[] Photo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FatherCNIC { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DOB { get; set; }
        public string MobileNo { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string CNICNo { get; set; }
        public string Gender { get; set; }
        public string Session { get; set; }
        public int SessionID { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramTitle { get; set; }
        public int DepartmentProgramID { get; set; }
        public Nullable<decimal> calc_EducationPercentage { get; set; }
        public Nullable<decimal> calc_TestPercentage { get; set; }
        public Nullable<decimal> calc_InterviewMarksPercentage { get; set; }
        public Nullable<decimal> AggregatePercentage { get; set; }
        public int AdmissionPreferenceID { get; set; }
        public Nullable<int> MeritListNo { get; set; }
        public Nullable<bool> IsAdmissionGranted { get; set; }
    }
}
