//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TestVouchers
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MobileNo { get; set; }
        public string CNICNo { get; set; }
        public string TestTitle { get; set; }
        public string TestSessionName { get; set; }
        public int VoucherNo { get; set; }
        public decimal Amount { get; set; }
        public int TestID { get; set; }
        public int TestSessionID { get; set; }
        public bool IsVerified { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> TestCalenderID { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string Attachment { get; set; }
        public int TestApplicantsID { get; set; }
        public bool IsFake { get; set; }
        public Nullable<System.DateTime> FakeDate { get; set; }
        public Nullable<int> FakeBy { get; set; }
        public string EmailAddress { get; set; }
        public bool IsAttend { get; set; }
    }
}
