//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TestAdmitCard
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MobileNo { get; set; }
        public string CNICNo { get; set; }
        public string TestTitle { get; set; }
        public string TestSession { get; set; }
        public string CenterName { get; set; }
        public string CenterAddress { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string PicturePath { get; set; }
        public byte[] Photo { get; set; }
        public int TestApplicantID { get; set; }
        public bool IsAttend { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
    }
}
