//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TestCalenders
    {
        public int ID { get; set; }
        public string TestTitle { get; set; }
        public string TestSession { get; set; }
        public string TestCenterName { get; set; }
        public int ApplicantID { get; set; }
        public int TestID { get; set; }
        public int TestCenterID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string CenterAddress { get; set; }
        public int TestApplicantID { get; set; }
        public int Slots { get; set; }
        public Nullable<int> TotalApplicants { get; set; }
        public Nullable<System.DateTime> SesstionStartDate { get; set; }
        public Nullable<System.DateTime> SessionEndDate { get; set; }
        public string TestLink { get; set; }
    }
}
